/**
 * §8.4a.10 W5 smoke probes — exercise all 4 tools via direct MCP Streamable HTTP.
 *
 * P1 tools/list, P2 query_corpus, P3 search_insights, P4 approve noop,
 * P5 capture_insight, P6 search includes pending, P7 approve reject path.
 */

const WORKER_URL = "https://spacesc-mcp.75xnd2784n.workers.dev/mcp";

let nextId = 1;
let sessionId = null;

async function rpc(method, params = {}) {
	const id = nextId++;
	const headers = {
		"Content-Type": "application/json",
		Accept: "application/json, text/event-stream",
	};
	if (sessionId) headers["mcp-session-id"] = sessionId;
	const resp = await fetch(WORKER_URL, {
		method: "POST",
		headers,
		body: JSON.stringify({ jsonrpc: "2.0", id, method, params }),
	});
	const sid = resp.headers.get("mcp-session-id");
	if (sid) sessionId = sid;
	const ct = resp.headers.get("content-type") || "";
	let body;
	if (ct.includes("event-stream")) {
		const text = await resp.text();
		const dataLines = text
			.split("\n")
			.filter((l) => l.startsWith("data:"))
			.map((l) => l.slice(5).trim())
			.filter(Boolean);
		body = dataLines.length ? JSON.parse(dataLines[dataLines.length - 1]) : null;
	} else {
		body = await resp.json();
	}
	return { status: resp.status, body };
}

async function init() {
	const { body } = await rpc("initialize", {
		protocolVersion: "2025-06-18",
		capabilities: {},
		clientInfo: { name: "spacesc-smoke", version: "1.0.0" },
	});
	console.log(`init: protocol=${body?.result?.protocolVersion}, server=${body?.result?.serverInfo?.name} v${body?.result?.serverInfo?.version}, sessionId=${sessionId?.slice(0, 8) ?? "?"}…`);
	const headers = { "Content-Type": "application/json", Accept: "application/json, text/event-stream" };
	if (sessionId) headers["mcp-session-id"] = sessionId;
	await fetch(WORKER_URL, {
		method: "POST",
		headers,
		body: JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }),
	});
}

async function call(toolName, args, label) {
	const { status, body } = await rpc("tools/call", { name: toolName, arguments: args });
	const isErr = body?.result?.isError;
	const text = body?.result?.content?.[0]?.text || JSON.stringify(body);
	const truncated = text.length > 700 ? text.slice(0, 700) + "…[truncated]" : text;
	console.log(`${label} [HTTP ${status}, isError=${isErr}]:\n  ${truncated}\n`);
	return { status, body };
}

await init();

console.log("=== P1: tools/list ===");
const listResp = await rpc("tools/list");
const tools = listResp.body?.result?.tools || [];
console.log(`tools registered: ${tools.length} (${tools.map((t) => t.name).join(", ")})\n`);

console.log("=== P2: query_corpus ===");
await call("query_corpus", { query: "AMTI export controls", limit: 2 }, "P2");

console.log("=== P3: search_insights (Mac online) ===");
const p3 = await call("search_insights", { query: "coalition data sharing", limit: 3 }, "P3");

const p3text = p3.body?.result?.content?.[0]?.text;
const p3parsed = p3text ? JSON.parse(p3text) : {};
const existingId = p3parsed?.results?.[0]?.insight_id;

console.log("=== P4: approve_insight noop (already-approved) ===");
if (existingId) {
	await call("approve_insight", { insight_id: existingId, action: "approve" }, "P4");
} else {
	console.log("P4 SKIPPED — no existing insights returned by P3\n");
}

console.log("=== P5: capture_insight (creates pending row) ===");
await call(
	"capture_insight",
	{
		claim: "W5 smoke probe insight: §8.4a.10 MCP server end-to-end test 2026-05-05",
		claim_type: "observation",
		domain_primary: "Cross-cutting",
		confidence: "low",
		query_context: "auto-generated by spacesc-mcp/smoke.mjs",
	},
	"P5",
);

console.log("=== P6: search_insights for the just-captured pending row ===");
const p6 = await call(
	"search_insights",
	{ query: "W5 smoke probe", include_pending: true, limit: 3 },
	"P6",
);
const p6text = p6.body?.result?.content?.[0]?.text;
const p6parsed = p6text ? JSON.parse(p6text) : {};
const pendingId = (p6parsed?.results || []).find((r) => r.status === "pending")?.insight_id;

if (pendingId) {
	console.log("=== P7: approve_insight reject (deletes pending P5 row) ===");
	await call("approve_insight", { insight_id: pendingId, action: "reject" }, "P7");
} else {
	console.log("P7 SKIPPED — could not locate pending P5 insight in P6 results\n");
}

console.log("smoke complete");
